### ISSUE TITLE
I really appreciate this repo, but...

### ISSUE THREAD

**Issue by Dan1jel** [rursache/qBittorrent-RaspberryPi#1]
My Raspberry Pi 3B have now been on 90-100% load under 2h, is this expected to take this long? to compile the files?
im lucky to have an aluminium block as a cover for the Pi otherwise it would be overheated.

**Comment by rursache** [comment]
i only tested on raspberry pi 4 where it's not taking longer than 30mins. use the pre-made debs or the docker container if you don't want to build from source

**Comment by Dan1jel** [comment]
> 

In otherwords, this is for 64bit only? (not for Raspberry pi:s older then v.4?)

**Comment by rursache** [comment]
no, the script supports both 32bit (armhf) and 64bit (arm64 and even amd64).
there is no reason to run 32bit OSes in 2022 tho
