### ISSUE TITLE
Odd messages when trying to install pre-build qB 4.4.5

### ISSUE THREAD

**Issue by crankynet** [rursache/qBittorrent-RaspberryPi#2]
(Reading database ... 42980 files and directories currently installed.)
Preparing to unpack .../qbittorrent_4.4.5-1_arm64.deb ...
Unpacking libtorrent (1.2.17-1) over (1.2.17-1) ...
Setting up libtorrent (1.2.17-1) ...

**Comment by rursache** [comment]
You didn't post the full log.

The provided deb files are for debian bullseye 64bit.

I've tested them yesterday and everything works

**Comment by crankynet** [comment]
Below is the full log, After the installation of 4.5.5 failed, I tried 4.4.3.1. That one failed as well because I don't have all the lib but that is to be expected.

`
qbtuser@k:~ $ sudo dpkg -i libtorrent_1.2.17-1_arm64.deb 

[sudo] password for qbtuser: 
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 42980 files and directories currently installed.)
Preparing to unpack libtorrent_1.2.17-1_arm64.deb ...
Unpacking libtorrent (1.2.17-1) over (1.2.17-1) ...
Setting up libtorrent (1.2.17-1) ...
qbtuser@k:~ $ sudo dpkg -i qbittorrent_4.4.5-1_arm64.deb 

(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 42980 files and directories currently installed.)
Preparing to unpack qbittorrent_4.4.5-1_arm64.deb ...
Unpacking libtorrent (1.2.17-1) over (1.2.17-1) ...
Setting up libtorrent (1.2.17-1) ...
qbtuser@k:~ $ sudo dpkg -i qbittorrent_4.4.5-1_arm64.deb / mnt/data/qbittorrent_4.4.3.1-1_arm64.deb 

(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 42980 files and directories currently installed.)
Preparing to unpack .../qbittorrent_4.4.3.1-1_arm64.deb ...
Unpacking qbittorrent (4.4.3.1) over (4.4.3.1) ...
dpkg: dependency problems prevent configuration of qbittorrent:
 qbittorrent depends on libqt5core5a (>= 5.10.0); however:
  Package libqt5core5a is not installed.
 qbittorrent depends on libqt5dbus5 (>= 5.2.0); however:
  Package libqt5dbus5 is not installed.
 qbittorrent depends on libqt5gui5 (>= 5.11.0~rc1) | libqt5gui5-gles (>= 5.11.0~rc1); however:
  Package libqt5gui5 is not installed.
  Package libqt5gui5-gles is not installed.
 qbittorrent depends on libqt5network5 (>= 5.9.0~beta); however:
  Package libqt5network5 is not installed.
 qbittorrent depends on libqt5widgets5 (>= 5.11.0~rc1); however:
  Package libqt5widgets5 is not installed.
 qbittorrent depends on libqt5xml5 (>= 5.2.0); however:
  Package libqt5xml5 is not installed.

dpkg: error processing package qbittorrent (--install):
 dependency problems - leaving unconfigured
Processing triggers for man-db (2.9.4-2) ...
Errors were encountered while processing:
 qbittorrent
`

**Comment by crankynet** [comment]
Output of uname -m
aarch64


Content of /etc/os-release

PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Comment by rursache** [comment]
install the missing packages (`Package **x** is not installed`) with `sudo apt-get -f install`

EDIT: also updated readme with the required dependencies as dpkg won't install them:
```
sudo apt install qt5-qmake qtbase5-dev qttools5-dev-tools libqt5svg5-dev geoip-database -y &&
sudo dpkg -i libtorrent*.deb &&
sudo dpkg -i qbittorrent*.deb
```
