### ISSUE TITLE
Odd messages when trying to install pre-build qB 4.4.5

### ISSUE THREAD

**Issue by crankynet** [rursache/qBittorrent-RaspberryPi#4]
When I open an issue yesterday, my point is not about install qB 4.4.3.1. I know how to install those missing packages. The issue is with 4.4.5. The full log is repeat here:

qbtuser@k:~ $ sudo dpkg -i qbittorrent_4.4.5-1_arm64.deb

(Reading database ...
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 42980 files and directories currently installed.)
Preparing to unpack qbittorrent_4.4.5-1_arm64.deb ...
Unpacking libtorrent (1.2.17-1) over (1.2.17-1) ...
Setting up libtorrent (1.2.17-1) ...

**Comment by rursache** [comment]
there are no errors in that log. 
all versions compile and install the same.
